package xio.helper
object XIOErrorHelperInstance {
  trait MatchAll1Apply1[P <: xio.nat.error.NatEither, E1, Input <: xio.nat.has.Nat, Out] {
    def input1[Out1 <: Out, Input1 <: xio.nat.has.Nat](e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1])(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]]
    ): xio.XIO[xio.XHasM1[Input]#InnerPlus[Input1], P, Out]
  }
  trait MatchAll1Apply2[P <: xio.nat.error.NatEither, E1, E2, Input <: xio.nat.has.Nat, Out] {
    def input2[Out1 <: Out, Input1 <: xio.nat.has.Nat, Out2 <: Out, Input2 <: xio.nat.has.Nat](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]]
    ): xio.XIO[xio.XHasM2[Input, Input1]#InnerPlus[Input2], P, Out]
  }
  trait MatchAll1Apply3[P <: xio.nat.error.NatEither, E1, E2, E3, Input <: xio.nat.has.Nat, Out] {
    def input3[Out1 <: Out, Input1 <: xio.nat.has.Nat, Out2 <: Out, Input2 <: xio.nat.has.Nat, Out3 <: Out, Input3 <: xio.nat.has.Nat](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]]
    ): xio.XIO[xio.XHasM3[Input, Input1, Input2]#InnerPlus[Input3], P, Out]
  }
  trait MatchAll1Apply4[P <: xio.nat.error.NatEither, E1, E2, E3, E4, Input <: xio.nat.has.Nat, Out] {
    def input4[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]]
    ): xio.XIO[xio.XHasM4[Input, Input1, Input2, Input3]#InnerPlus[Input4], P, Out]
  }
  trait MatchAll1Apply5[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, Input <: xio.nat.has.Nat, Out] {
    def input5[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]]
    ): xio.XIO[xio.XHasM5[Input, Input1, Input2, Input3, Input4]#InnerPlus[Input5], P, Out]
  }
  trait MatchAll1Apply6[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, Input <: xio.nat.has.Nat, Out] {
    def input6[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]]
    ): xio.XIO[xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]#InnerPlus[Input6], P, Out]
  }
  trait MatchAll1Apply7[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, Input <: xio.nat.has.Nat, Out] {
    def input7[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]]
    ): xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out]
  }
  trait MatchAll1Apply8[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, Input <: xio.nat.has.Nat, Out] {
    def input8[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]]
    ): xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out]
  }
  trait MatchAll1Apply9[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, Input <: xio.nat.has.Nat, Out] {
    def input9[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]]
    ): xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out]
  }
  trait MatchAll1Apply10[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, Input <: xio.nat.has.Nat, Out] {
    def input10[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]]
    ): xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out]
  }
  trait MatchAll1Apply11[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, Input <: xio.nat.has.Nat, Out] {
    def input11[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]]
    ): xio.XIO[xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11], P, Out]
  }
  trait MatchAll1Apply12[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, Input <: xio.nat.has.Nat, Out] {
    def input12[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]]
    ): xio.XIO[xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12], P, Out]
  }
  trait MatchAll1Apply13[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, Input <: xio.nat.has.Nat, Out] {
    def input13[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]]
    ): xio.XIO[xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13], P, Out]
  }
  trait MatchAll1Apply14[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, Input <: xio.nat.has.Nat, Out] {
    def input14[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]]
    ): xio.XIO[xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14], P, Out]
  }
  trait MatchAll1Apply15[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, Input <: xio.nat.has.Nat, Out] {
    def input15[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat,
      Out15 <: Out,
      Input15 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14],
      e15: xio.ErrorContent[E15, P] => xio.XIO[Input15, P, Out15]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]],
      natReversePlus15: xio.nat.has.NatReversePlus[Input15, xio.XHasM15[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14
      ]]
    ): xio.XIO[xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[
      Input15
    ], P, Out]
  }
  trait MatchAll1Apply16[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, Input <: xio.nat.has.Nat, Out] {
    def input16[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat,
      Out15 <: Out,
      Input15 <: xio.nat.has.Nat,
      Out16 <: Out,
      Input16 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14],
      e15: xio.ErrorContent[E15, P] => xio.XIO[Input15, P, Out15],
      e16: xio.ErrorContent[E16, P] => xio.XIO[Input16, P, Out16]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]],
      natReversePlus15: xio.nat.has.NatReversePlus[Input15, xio.XHasM15[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14
      ]],
      natReversePlus16: xio.nat.has.NatReversePlus[Input16, xio.XHasM16[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15
      ]]
    ): xio.XIO[xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[
      Input16
    ], P, Out]
  }
  trait MatchAll1Apply17[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, Input <: xio.nat.has.Nat, Out] {
    def input17[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat,
      Out15 <: Out,
      Input15 <: xio.nat.has.Nat,
      Out16 <: Out,
      Input16 <: xio.nat.has.Nat,
      Out17 <: Out,
      Input17 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14],
      e15: xio.ErrorContent[E15, P] => xio.XIO[Input15, P, Out15],
      e16: xio.ErrorContent[E16, P] => xio.XIO[Input16, P, Out16],
      e17: xio.ErrorContent[E17, P] => xio.XIO[Input17, P, Out17]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]],
      natReversePlus15: xio.nat.has.NatReversePlus[Input15, xio.XHasM15[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14
      ]],
      natReversePlus16: xio.nat.has.NatReversePlus[Input16, xio.XHasM16[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15
      ]],
      natReversePlus17: xio.nat.has.NatReversePlus[Input17, xio.XHasM17[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16
      ]]
    ): xio.XIO[
      xio.XHasM17[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15, Input16]#InnerPlus[
        Input17
      ],
      P,
      Out
    ]
  }
  trait MatchAll1Apply18[P <: xio.nat.error.NatEither, E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, Input <: xio.nat.has.Nat, Out] {
    def input18[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat,
      Out15 <: Out,
      Input15 <: xio.nat.has.Nat,
      Out16 <: Out,
      Input16 <: xio.nat.has.Nat,
      Out17 <: Out,
      Input17 <: xio.nat.has.Nat,
      Out18 <: Out,
      Input18 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14],
      e15: xio.ErrorContent[E15, P] => xio.XIO[Input15, P, Out15],
      e16: xio.ErrorContent[E16, P] => xio.XIO[Input16, P, Out16],
      e17: xio.ErrorContent[E17, P] => xio.XIO[Input17, P, Out17],
      e18: xio.ErrorContent[E18, P] => xio.XIO[Input18, P, Out18]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]],
      natReversePlus15: xio.nat.has.NatReversePlus[Input15, xio.XHasM15[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14
      ]],
      natReversePlus16: xio.nat.has.NatReversePlus[Input16, xio.XHasM16[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15
      ]],
      natReversePlus17: xio.nat.has.NatReversePlus[Input17, xio.XHasM17[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16
      ]],
      natReversePlus18: xio.nat.has.NatReversePlus[Input18, xio.XHasM18[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17
      ]]
    ): xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out]
  }
  trait MatchAll1Apply19[
    P <: xio.nat.error.NatEither,
    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
    E7,
    E8,
    E9,
    E10,
    E11,
    E12,
    E13,
    E14,
    E15,
    E16,
    E17,
    E18,
    E19,
    Input <: xio.nat.has.Nat,
    Out
  ] {
    def input19[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat,
      Out15 <: Out,
      Input15 <: xio.nat.has.Nat,
      Out16 <: Out,
      Input16 <: xio.nat.has.Nat,
      Out17 <: Out,
      Input17 <: xio.nat.has.Nat,
      Out18 <: Out,
      Input18 <: xio.nat.has.Nat,
      Out19 <: Out,
      Input19 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14],
      e15: xio.ErrorContent[E15, P] => xio.XIO[Input15, P, Out15],
      e16: xio.ErrorContent[E16, P] => xio.XIO[Input16, P, Out16],
      e17: xio.ErrorContent[E17, P] => xio.XIO[Input17, P, Out17],
      e18: xio.ErrorContent[E18, P] => xio.XIO[Input18, P, Out18],
      e19: xio.ErrorContent[E19, P] => xio.XIO[Input19, P, Out19]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]],
      natReversePlus15: xio.nat.has.NatReversePlus[Input15, xio.XHasM15[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14
      ]],
      natReversePlus16: xio.nat.has.NatReversePlus[Input16, xio.XHasM16[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15
      ]],
      natReversePlus17: xio.nat.has.NatReversePlus[Input17, xio.XHasM17[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16
      ]],
      natReversePlus18: xio.nat.has.NatReversePlus[Input18, xio.XHasM18[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17
      ]],
      natReversePlus19: xio.nat.has.NatReversePlus[Input19, xio.XHasM19[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18
      ]]
    ): xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out]
  }
  trait MatchAll1Apply20[
    P <: xio.nat.error.NatEither,
    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
    E7,
    E8,
    E9,
    E10,
    E11,
    E12,
    E13,
    E14,
    E15,
    E16,
    E17,
    E18,
    E19,
    E20,
    Input <: xio.nat.has.Nat,
    Out
  ] {
    def input20[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat,
      Out15 <: Out,
      Input15 <: xio.nat.has.Nat,
      Out16 <: Out,
      Input16 <: xio.nat.has.Nat,
      Out17 <: Out,
      Input17 <: xio.nat.has.Nat,
      Out18 <: Out,
      Input18 <: xio.nat.has.Nat,
      Out19 <: Out,
      Input19 <: xio.nat.has.Nat,
      Out20 <: Out,
      Input20 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14],
      e15: xio.ErrorContent[E15, P] => xio.XIO[Input15, P, Out15],
      e16: xio.ErrorContent[E16, P] => xio.XIO[Input16, P, Out16],
      e17: xio.ErrorContent[E17, P] => xio.XIO[Input17, P, Out17],
      e18: xio.ErrorContent[E18, P] => xio.XIO[Input18, P, Out18],
      e19: xio.ErrorContent[E19, P] => xio.XIO[Input19, P, Out19],
      e20: xio.ErrorContent[E20, P] => xio.XIO[Input20, P, Out20]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]],
      natReversePlus15: xio.nat.has.NatReversePlus[Input15, xio.XHasM15[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14
      ]],
      natReversePlus16: xio.nat.has.NatReversePlus[Input16, xio.XHasM16[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15
      ]],
      natReversePlus17: xio.nat.has.NatReversePlus[Input17, xio.XHasM17[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16
      ]],
      natReversePlus18: xio.nat.has.NatReversePlus[Input18, xio.XHasM18[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17
      ]],
      natReversePlus19: xio.nat.has.NatReversePlus[Input19, xio.XHasM19[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18
      ]],
      natReversePlus20: xio.nat.has.NatReversePlus[Input20, xio.XHasM20[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18,
        Input19
      ]]
    ): xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out]
  }
  trait MatchAll1Apply21[
    P <: xio.nat.error.NatEither,
    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
    E7,
    E8,
    E9,
    E10,
    E11,
    E12,
    E13,
    E14,
    E15,
    E16,
    E17,
    E18,
    E19,
    E20,
    E21,
    Input <: xio.nat.has.Nat,
    Out
  ] {
    def input21[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat,
      Out15 <: Out,
      Input15 <: xio.nat.has.Nat,
      Out16 <: Out,
      Input16 <: xio.nat.has.Nat,
      Out17 <: Out,
      Input17 <: xio.nat.has.Nat,
      Out18 <: Out,
      Input18 <: xio.nat.has.Nat,
      Out19 <: Out,
      Input19 <: xio.nat.has.Nat,
      Out20 <: Out,
      Input20 <: xio.nat.has.Nat,
      Out21 <: Out,
      Input21 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14],
      e15: xio.ErrorContent[E15, P] => xio.XIO[Input15, P, Out15],
      e16: xio.ErrorContent[E16, P] => xio.XIO[Input16, P, Out16],
      e17: xio.ErrorContent[E17, P] => xio.XIO[Input17, P, Out17],
      e18: xio.ErrorContent[E18, P] => xio.XIO[Input18, P, Out18],
      e19: xio.ErrorContent[E19, P] => xio.XIO[Input19, P, Out19],
      e20: xio.ErrorContent[E20, P] => xio.XIO[Input20, P, Out20],
      e21: xio.ErrorContent[E21, P] => xio.XIO[Input21, P, Out21]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]],
      natReversePlus15: xio.nat.has.NatReversePlus[Input15, xio.XHasM15[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14
      ]],
      natReversePlus16: xio.nat.has.NatReversePlus[Input16, xio.XHasM16[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15
      ]],
      natReversePlus17: xio.nat.has.NatReversePlus[Input17, xio.XHasM17[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16
      ]],
      natReversePlus18: xio.nat.has.NatReversePlus[Input18, xio.XHasM18[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17
      ]],
      natReversePlus19: xio.nat.has.NatReversePlus[Input19, xio.XHasM19[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18
      ]],
      natReversePlus20: xio.nat.has.NatReversePlus[Input20, xio.XHasM20[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18,
        Input19
      ]],
      natReversePlus21: xio.nat.has.NatReversePlus[Input21, xio.XHasM21[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18,
        Input19,
        Input20
      ]]
    ): xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out]
  }
  trait MatchAll1Apply22[
    P <: xio.nat.error.NatEither,
    E1,
    E2,
    E3,
    E4,
    E5,
    E6,
    E7,
    E8,
    E9,
    E10,
    E11,
    E12,
    E13,
    E14,
    E15,
    E16,
    E17,
    E18,
    E19,
    E20,
    E21,
    E22,
    Input <: xio.nat.has.Nat,
    Out
  ] {
    def input22[
      Out1 <: Out,
      Input1 <: xio.nat.has.Nat,
      Out2 <: Out,
      Input2 <: xio.nat.has.Nat,
      Out3 <: Out,
      Input3 <: xio.nat.has.Nat,
      Out4 <: Out,
      Input4 <: xio.nat.has.Nat,
      Out5 <: Out,
      Input5 <: xio.nat.has.Nat,
      Out6 <: Out,
      Input6 <: xio.nat.has.Nat,
      Out7 <: Out,
      Input7 <: xio.nat.has.Nat,
      Out8 <: Out,
      Input8 <: xio.nat.has.Nat,
      Out9 <: Out,
      Input9 <: xio.nat.has.Nat,
      Out10 <: Out,
      Input10 <: xio.nat.has.Nat,
      Out11 <: Out,
      Input11 <: xio.nat.has.Nat,
      Out12 <: Out,
      Input12 <: xio.nat.has.Nat,
      Out13 <: Out,
      Input13 <: xio.nat.has.Nat,
      Out14 <: Out,
      Input14 <: xio.nat.has.Nat,
      Out15 <: Out,
      Input15 <: xio.nat.has.Nat,
      Out16 <: Out,
      Input16 <: xio.nat.has.Nat,
      Out17 <: Out,
      Input17 <: xio.nat.has.Nat,
      Out18 <: Out,
      Input18 <: xio.nat.has.Nat,
      Out19 <: Out,
      Input19 <: xio.nat.has.Nat,
      Out20 <: Out,
      Input20 <: xio.nat.has.Nat,
      Out21 <: Out,
      Input21 <: xio.nat.has.Nat,
      Out22 <: Out,
      Input22 <: xio.nat.has.Nat
    ](
      e1: xio.ErrorContent[E1, P] => xio.XIO[Input1, P, Out1],
      e2: xio.ErrorContent[E2, P] => xio.XIO[Input2, P, Out2],
      e3: xio.ErrorContent[E3, P] => xio.XIO[Input3, P, Out3],
      e4: xio.ErrorContent[E4, P] => xio.XIO[Input4, P, Out4],
      e5: xio.ErrorContent[E5, P] => xio.XIO[Input5, P, Out5],
      e6: xio.ErrorContent[E6, P] => xio.XIO[Input6, P, Out6],
      e7: xio.ErrorContent[E7, P] => xio.XIO[Input7, P, Out7],
      e8: xio.ErrorContent[E8, P] => xio.XIO[Input8, P, Out8],
      e9: xio.ErrorContent[E9, P] => xio.XIO[Input9, P, Out9],
      e10: xio.ErrorContent[E10, P] => xio.XIO[Input10, P, Out10],
      e11: xio.ErrorContent[E11, P] => xio.XIO[Input11, P, Out11],
      e12: xio.ErrorContent[E12, P] => xio.XIO[Input12, P, Out12],
      e13: xio.ErrorContent[E13, P] => xio.XIO[Input13, P, Out13],
      e14: xio.ErrorContent[E14, P] => xio.XIO[Input14, P, Out14],
      e15: xio.ErrorContent[E15, P] => xio.XIO[Input15, P, Out15],
      e16: xio.ErrorContent[E16, P] => xio.XIO[Input16, P, Out16],
      e17: xio.ErrorContent[E17, P] => xio.XIO[Input17, P, Out17],
      e18: xio.ErrorContent[E18, P] => xio.XIO[Input18, P, Out18],
      e19: xio.ErrorContent[E19, P] => xio.XIO[Input19, P, Out19],
      e20: xio.ErrorContent[E20, P] => xio.XIO[Input20, P, Out20],
      e21: xio.ErrorContent[E21, P] => xio.XIO[Input21, P, Out21],
      e22: xio.ErrorContent[E22, P] => xio.XIO[Input22, P, Out22]
    )(implicit
      natReversePlus1: xio.nat.has.NatReversePlus[Input1, xio.XHasM1[Input]],
      natReversePlus2: xio.nat.has.NatReversePlus[Input2, xio.XHasM2[Input, Input1]],
      natReversePlus3: xio.nat.has.NatReversePlus[Input3, xio.XHasM3[Input, Input1, Input2]],
      natReversePlus4: xio.nat.has.NatReversePlus[Input4, xio.XHasM4[Input, Input1, Input2, Input3]],
      natReversePlus5: xio.nat.has.NatReversePlus[Input5, xio.XHasM5[Input, Input1, Input2, Input3, Input4]],
      natReversePlus6: xio.nat.has.NatReversePlus[Input6, xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]],
      natReversePlus7: xio.nat.has.NatReversePlus[Input7, xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]],
      natReversePlus8: xio.nat.has.NatReversePlus[Input8, xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]],
      natReversePlus9: xio.nat.has.NatReversePlus[Input9, xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]],
      natReversePlus10: xio.nat.has.NatReversePlus[Input10, xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]],
      natReversePlus11: xio.nat.has.NatReversePlus[Input11, xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]],
      natReversePlus12: xio.nat.has.NatReversePlus[Input12, xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]],
      natReversePlus13: xio.nat.has.NatReversePlus[Input13, xio.XHasM13[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12
      ]],
      natReversePlus14: xio.nat.has.NatReversePlus[Input14, xio.XHasM14[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13
      ]],
      natReversePlus15: xio.nat.has.NatReversePlus[Input15, xio.XHasM15[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14
      ]],
      natReversePlus16: xio.nat.has.NatReversePlus[Input16, xio.XHasM16[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15
      ]],
      natReversePlus17: xio.nat.has.NatReversePlus[Input17, xio.XHasM17[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16
      ]],
      natReversePlus18: xio.nat.has.NatReversePlus[Input18, xio.XHasM18[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17
      ]],
      natReversePlus19: xio.nat.has.NatReversePlus[Input19, xio.XHasM19[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18
      ]],
      natReversePlus20: xio.nat.has.NatReversePlus[Input20, xio.XHasM20[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18,
        Input19
      ]],
      natReversePlus21: xio.nat.has.NatReversePlus[Input21, xio.XHasM21[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18,
        Input19,
        Input20
      ]],
      natReversePlus22: xio.nat.has.NatReversePlus[Input22, xio.XHasM22[
        Input,
        Input1,
        Input2,
        Input3,
        Input4,
        Input5,
        Input6,
        Input7,
        Input8,
        Input9,
        Input10,
        Input11,
        Input12,
        Input13,
        Input14,
        Input15,
        Input16,
        Input17,
        Input18,
        Input19,
        Input20,
        Input21
      ]]
    ): xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out]
  }
}
