package xio.helper
object XIOErrorHelperInstance2 {
  def errorCompat1[P <: xio.nat.error.NatEither, E1, Input1 <: xio.nat.has.Nat, Input <: xio.nat.has.Nat, Out](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM2[Input, Input1], P, Out],
    u: xio.XError1[E1]
  ): xio.XIO[Input#InnerPlus[Input1], P, Out] = e1(new xio.ErrorContentImpl(u.sureRight))
  def errorCompat2[P <: xio.nat.error.NatEither, E1, Input1 <: xio.nat.has.Nat, E2, Input2 <: xio.nat.has.Nat, Input <: xio.nat.has.Nat, Out](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM2[Input, Input1]#InnerPlus[Input2], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM2[Input, Input1]#InnerPlus[Input2], P, Out],
    u: xio.XError2[E1, E2]
  ): xio.XIO[xio.XHasM2[Input, Input1]#InnerPlus[Input2], P, Out] = u.either.fold(ii1 => errorCompat1(e1, ii1), ii2 => e2(new xio.ErrorContentImpl(ii2)))
  def errorCompat3[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM3[Input, Input1, Input2]#InnerPlus[Input3], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM3[Input, Input1, Input2]#InnerPlus[Input3], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM3[Input, Input1, Input2]#InnerPlus[Input3], P, Out],
    u: xio.XError3[E1, E2, E3]
  ): xio.XIO[xio.XHasM3[Input, Input1, Input2]#InnerPlus[Input3], P, Out] = u.either.fold(ii1 => errorCompat2(e1, e2, ii1), ii2 => e3(new xio.ErrorContentImpl(ii2)))
  def errorCompat4[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM4[Input, Input1, Input2, Input3]#InnerPlus[Input4], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM4[Input, Input1, Input2, Input3]#InnerPlus[Input4], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM4[Input, Input1, Input2, Input3]#InnerPlus[Input4], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM4[Input, Input1, Input2, Input3]#InnerPlus[Input4], P, Out],
    u: xio.XError4[E1, E2, E3, E4]
  ): xio.XIO[xio.XHasM4[Input, Input1, Input2, Input3]#InnerPlus[Input4], P, Out] =
    u.either.fold(ii1 => errorCompat3(e1, e2, e3, ii1), ii2 => e4(new xio.ErrorContentImpl(ii2)))
  def errorCompat5[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM5[Input, Input1, Input2, Input3, Input4]#InnerPlus[Input5], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM5[Input, Input1, Input2, Input3, Input4]#InnerPlus[Input5], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM5[Input, Input1, Input2, Input3, Input4]#InnerPlus[Input5], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM5[Input, Input1, Input2, Input3, Input4]#InnerPlus[Input5], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM5[Input, Input1, Input2, Input3, Input4]#InnerPlus[Input5], P, Out],
    u: xio.XError5[E1, E2, E3, E4, E5]
  ): xio.XIO[xio.XHasM5[Input, Input1, Input2, Input3, Input4]#InnerPlus[Input5], P, Out] =
    u.either.fold(ii1 => errorCompat4(e1, e2, e3, e4, ii1), ii2 => e5(new xio.ErrorContentImpl(ii2)))
  def errorCompat6[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]#InnerPlus[Input6], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]#InnerPlus[Input6], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]#InnerPlus[Input6], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]#InnerPlus[Input6], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]#InnerPlus[Input6], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]#InnerPlus[Input6], P, Out],
    u: xio.XError6[E1, E2, E3, E4, E5, E6]
  ): xio.XIO[xio.XHasM6[Input, Input1, Input2, Input3, Input4, Input5]#InnerPlus[Input6], P, Out] =
    u.either.fold(ii1 => errorCompat5(e1, e2, e3, e4, e5, ii1), ii2 => e6(new xio.ErrorContentImpl(ii2)))
  def errorCompat7[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out],
    u: xio.XError7[E1, E2, E3, E4, E5, E6, E7]
  ): xio.XIO[xio.XHasM7[Input, Input1, Input2, Input3, Input4, Input5, Input6]#InnerPlus[Input7], P, Out] =
    u.either.fold(ii1 => errorCompat6(e1, e2, e3, e4, e5, e6, ii1), ii2 => e7(new xio.ErrorContentImpl(ii2)))
  def errorCompat8[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out],
    u: xio.XError8[E1, E2, E3, E4, E5, E6, E7, E8]
  ): xio.XIO[xio.XHasM8[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7]#InnerPlus[Input8], P, Out] =
    u.either.fold(ii1 => errorCompat7(e1, e2, e3, e4, e5, e6, e7, ii1), ii2 => e8(new xio.ErrorContentImpl(ii2)))
  def errorCompat9[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    e9: xio.ErrorContent[E9, P] => xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out],
    u: xio.XError9[E1, E2, E3, E4, E5, E6, E7, E8, E9]
  ): xio.XIO[xio.XHasM9[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8]#InnerPlus[Input9], P, Out] =
    u.either.fold(ii1 => errorCompat8(e1, e2, e3, e4, e5, e6, e7, e8, ii1), ii2 => e9(new xio.ErrorContentImpl(ii2)))
  def errorCompat10[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e9: xio.ErrorContent[E9, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    e10: xio.ErrorContent[E10, P] => xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out],
    u: xio.XError10[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10]
  ): xio.XIO[xio.XHasM10[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9]#InnerPlus[Input10], P, Out] =
    u.either.fold(ii1 => errorCompat9(e1, e2, e3, e4, e5, e6, e7, e8, e9, ii1), ii2 => e10(new xio.ErrorContentImpl(ii2)))
  def errorCompat11[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e2: xio.ErrorContent[E2, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e3: xio.ErrorContent[E3, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e4: xio.ErrorContent[E4, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e5: xio.ErrorContent[E5, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e6: xio.ErrorContent[E6, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e7: xio.ErrorContent[E7, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e8: xio.ErrorContent[E8, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e9: xio.ErrorContent[E9, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e10: xio.ErrorContent[E10, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    e11: xio.ErrorContent[E11, P] => xio.XIO[
      xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11],
      P,
      Out
    ],
    u: xio.XError11[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11]
  ): xio.XIO[xio.XHasM11[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10]#InnerPlus[Input11], P, Out] =
    u.either.fold(ii1 => errorCompat10(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, ii1), ii2 => e11(new xio.ErrorContentImpl(ii2)))
  def errorCompat12[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e2: xio.ErrorContent[E2, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e3: xio.ErrorContent[E3, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e4: xio.ErrorContent[E4, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e5: xio.ErrorContent[E5, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e6: xio.ErrorContent[E6, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e7: xio.ErrorContent[E7, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e8: xio.ErrorContent[E8, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e9: xio.ErrorContent[E9, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e10: xio.ErrorContent[E10, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e11: xio.ErrorContent[E11, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    e12: xio.ErrorContent[E12, P] => xio.XIO[
      xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12],
      P,
      Out
    ],
    u: xio.XError12[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12]
  ): xio.XIO[xio.XHasM12[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11]#InnerPlus[Input12], P, Out] =
    u.either.fold(ii1 => errorCompat11(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, ii1), ii2 => e12(new xio.ErrorContentImpl(ii2)))
  def errorCompat13[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e2: xio.ErrorContent[E2, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e3: xio.ErrorContent[E3, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e4: xio.ErrorContent[E4, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e5: xio.ErrorContent[E5, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e6: xio.ErrorContent[E6, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e7: xio.ErrorContent[E7, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e8: xio.ErrorContent[E8, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e9: xio.ErrorContent[E9, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e10: xio.ErrorContent[E10, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e11: xio.ErrorContent[E11, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e12: xio.ErrorContent[E12, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    e13: xio.ErrorContent[E13, P] => xio.XIO[
      xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13],
      P,
      Out
    ],
    u: xio.XError13[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13]
  ): xio.XIO[xio.XHasM13[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12]#InnerPlus[Input13], P, Out] =
    u.either.fold(ii1 => errorCompat12(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, ii1), ii2 => e13(new xio.ErrorContentImpl(ii2)))
  def errorCompat14[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e2: xio.ErrorContent[E2, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e3: xio.ErrorContent[E3, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e4: xio.ErrorContent[E4, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e5: xio.ErrorContent[E5, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e6: xio.ErrorContent[E6, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e7: xio.ErrorContent[E7, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e8: xio.ErrorContent[E8, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e9: xio.ErrorContent[E9, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e10: xio.ErrorContent[E10, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e11: xio.ErrorContent[E11, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e12: xio.ErrorContent[E12, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e13: xio.ErrorContent[E13, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    e14: xio.ErrorContent[E14, P] => xio.XIO[
      xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14],
      P,
      Out
    ],
    u: xio.XError14[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14]
  ): xio.XIO[xio.XHasM14[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13]#InnerPlus[Input14], P, Out] =
    u.either.fold(ii1 => errorCompat13(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, ii1), ii2 => e14(new xio.ErrorContentImpl(ii2)))
  def errorCompat15[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    E15,
    Input15 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e2: xio.ErrorContent[E2, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e3: xio.ErrorContent[E3, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e4: xio.ErrorContent[E4, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e5: xio.ErrorContent[E5, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e6: xio.ErrorContent[E6, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e7: xio.ErrorContent[E7, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e8: xio.ErrorContent[E8, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e9: xio.ErrorContent[E9, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e10: xio.ErrorContent[E10, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e11: xio.ErrorContent[E11, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e12: xio.ErrorContent[E12, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e13: xio.ErrorContent[E13, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e14: xio.ErrorContent[E14, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    e15: xio.ErrorContent[E15, P] => xio.XIO[
      xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[Input15],
      P,
      Out
    ],
    u: xio.XError15[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15]
  ): xio.XIO[xio.XHasM15[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14]#InnerPlus[
    Input15
  ], P, Out] = u.either.fold(ii1 => errorCompat14(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, ii1), ii2 => e15(new xio.ErrorContentImpl(ii2)))
  def errorCompat16[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    E15,
    Input15 <: xio.nat.has.Nat,
    E16,
    Input16 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e2: xio.ErrorContent[E2, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e3: xio.ErrorContent[E3, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e4: xio.ErrorContent[E4, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e5: xio.ErrorContent[E5, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e6: xio.ErrorContent[E6, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e7: xio.ErrorContent[E7, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e8: xio.ErrorContent[E8, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e9: xio.ErrorContent[E9, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e10: xio.ErrorContent[E10, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e11: xio.ErrorContent[E11, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e12: xio.ErrorContent[E12, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e13: xio.ErrorContent[E13, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e14: xio.ErrorContent[E14, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e15: xio.ErrorContent[E15, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    e16: xio.ErrorContent[E16, P] => xio.XIO[
      xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[Input16],
      P,
      Out
    ],
    u: xio.XError16[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16]
  ): xio.XIO[xio.XHasM16[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15]#InnerPlus[
    Input16
  ], P, Out] = u.either.fold(ii1 => errorCompat15(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, ii1), ii2 => e16(new xio.ErrorContentImpl(ii2)))
  def errorCompat17[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    E15,
    Input15 <: xio.nat.has.Nat,
    E16,
    Input16 <: xio.nat.has.Nat,
    E17,
    Input17 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e9: xio.ErrorContent[E9, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e10: xio.ErrorContent[E10, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e11: xio.ErrorContent[E11, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e12: xio.ErrorContent[E12, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e13: xio.ErrorContent[E13, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e14: xio.ErrorContent[E14, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e15: xio.ErrorContent[E15, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e16: xio.ErrorContent[E16, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    e17: xio.ErrorContent[E17, P] => xio.XIO[xio.XHasM17[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16
    ]#InnerPlus[Input17], P, Out],
    u: xio.XError17[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17]
  ): xio.XIO[
    xio.XHasM17[Input, Input1, Input2, Input3, Input4, Input5, Input6, Input7, Input8, Input9, Input10, Input11, Input12, Input13, Input14, Input15, Input16]#InnerPlus[
      Input17
    ],
    P,
    Out
  ] = u.either.fold(ii1 => errorCompat16(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, ii1), ii2 => e17(new xio.ErrorContentImpl(ii2)))
  def errorCompat18[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    E15,
    Input15 <: xio.nat.has.Nat,
    E16,
    Input16 <: xio.nat.has.Nat,
    E17,
    Input17 <: xio.nat.has.Nat,
    E18,
    Input18 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e9: xio.ErrorContent[E9, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e10: xio.ErrorContent[E10, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e11: xio.ErrorContent[E11, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e12: xio.ErrorContent[E12, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e13: xio.ErrorContent[E13, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e14: xio.ErrorContent[E14, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e15: xio.ErrorContent[E15, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e16: xio.ErrorContent[E16, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e17: xio.ErrorContent[E17, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    e18: xio.ErrorContent[E18, P] => xio.XIO[xio.XHasM18[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17
    ]#InnerPlus[Input18], P, Out],
    u: xio.XError18[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18]
  ): xio.XIO[xio.XHasM18[
    Input,
    Input1,
    Input2,
    Input3,
    Input4,
    Input5,
    Input6,
    Input7,
    Input8,
    Input9,
    Input10,
    Input11,
    Input12,
    Input13,
    Input14,
    Input15,
    Input16,
    Input17
  ]#InnerPlus[Input18], P, Out] =
    u.either.fold(ii1 => errorCompat17(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, ii1), ii2 => e18(new xio.ErrorContentImpl(ii2)))
  def errorCompat19[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    E15,
    Input15 <: xio.nat.has.Nat,
    E16,
    Input16 <: xio.nat.has.Nat,
    E17,
    Input17 <: xio.nat.has.Nat,
    E18,
    Input18 <: xio.nat.has.Nat,
    E19,
    Input19 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e9: xio.ErrorContent[E9, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e10: xio.ErrorContent[E10, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e11: xio.ErrorContent[E11, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e12: xio.ErrorContent[E12, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e13: xio.ErrorContent[E13, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e14: xio.ErrorContent[E14, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e15: xio.ErrorContent[E15, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e16: xio.ErrorContent[E16, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e17: xio.ErrorContent[E17, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e18: xio.ErrorContent[E18, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    e19: xio.ErrorContent[E19, P] => xio.XIO[xio.XHasM19[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18
    ]#InnerPlus[Input19], P, Out],
    u: xio.XError19[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19]
  ): xio.XIO[xio.XHasM19[
    Input,
    Input1,
    Input2,
    Input3,
    Input4,
    Input5,
    Input6,
    Input7,
    Input8,
    Input9,
    Input10,
    Input11,
    Input12,
    Input13,
    Input14,
    Input15,
    Input16,
    Input17,
    Input18
  ]#InnerPlus[Input19], P, Out] =
    u.either.fold(ii1 => errorCompat18(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, ii1), ii2 => e19(new xio.ErrorContentImpl(ii2)))
  def errorCompat20[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    E15,
    Input15 <: xio.nat.has.Nat,
    E16,
    Input16 <: xio.nat.has.Nat,
    E17,
    Input17 <: xio.nat.has.Nat,
    E18,
    Input18 <: xio.nat.has.Nat,
    E19,
    Input19 <: xio.nat.has.Nat,
    E20,
    Input20 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e9: xio.ErrorContent[E9, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e10: xio.ErrorContent[E10, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e11: xio.ErrorContent[E11, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e12: xio.ErrorContent[E12, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e13: xio.ErrorContent[E13, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e14: xio.ErrorContent[E14, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e15: xio.ErrorContent[E15, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e16: xio.ErrorContent[E16, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e17: xio.ErrorContent[E17, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e18: xio.ErrorContent[E18, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e19: xio.ErrorContent[E19, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    e20: xio.ErrorContent[E20, P] => xio.XIO[xio.XHasM20[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19
    ]#InnerPlus[Input20], P, Out],
    u: xio.XError20[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20]
  ): xio.XIO[xio.XHasM20[
    Input,
    Input1,
    Input2,
    Input3,
    Input4,
    Input5,
    Input6,
    Input7,
    Input8,
    Input9,
    Input10,
    Input11,
    Input12,
    Input13,
    Input14,
    Input15,
    Input16,
    Input17,
    Input18,
    Input19
  ]#InnerPlus[Input20], P, Out] =
    u.either
      .fold(ii1 => errorCompat19(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, ii1), ii2 => e20(new xio.ErrorContentImpl(ii2)))
  def errorCompat21[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    E15,
    Input15 <: xio.nat.has.Nat,
    E16,
    Input16 <: xio.nat.has.Nat,
    E17,
    Input17 <: xio.nat.has.Nat,
    E18,
    Input18 <: xio.nat.has.Nat,
    E19,
    Input19 <: xio.nat.has.Nat,
    E20,
    Input20 <: xio.nat.has.Nat,
    E21,
    Input21 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e9: xio.ErrorContent[E9, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e10: xio.ErrorContent[E10, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e11: xio.ErrorContent[E11, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e12: xio.ErrorContent[E12, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e13: xio.ErrorContent[E13, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e14: xio.ErrorContent[E14, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e15: xio.ErrorContent[E15, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e16: xio.ErrorContent[E16, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e17: xio.ErrorContent[E17, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e18: xio.ErrorContent[E18, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e19: xio.ErrorContent[E19, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e20: xio.ErrorContent[E20, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    e21: xio.ErrorContent[E21, P] => xio.XIO[xio.XHasM21[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20
    ]#InnerPlus[Input21], P, Out],
    u: xio.XError21[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21]
  ): xio.XIO[xio.XHasM21[
    Input,
    Input1,
    Input2,
    Input3,
    Input4,
    Input5,
    Input6,
    Input7,
    Input8,
    Input9,
    Input10,
    Input11,
    Input12,
    Input13,
    Input14,
    Input15,
    Input16,
    Input17,
    Input18,
    Input19,
    Input20
  ]#InnerPlus[Input21], P, Out] =
    u.either.fold(
      ii1 => errorCompat20(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, ii1),
      ii2 => e21(new xio.ErrorContentImpl(ii2))
    )
  def errorCompat22[
    P <: xio.nat.error.NatEither,
    E1,
    Input1 <: xio.nat.has.Nat,
    E2,
    Input2 <: xio.nat.has.Nat,
    E3,
    Input3 <: xio.nat.has.Nat,
    E4,
    Input4 <: xio.nat.has.Nat,
    E5,
    Input5 <: xio.nat.has.Nat,
    E6,
    Input6 <: xio.nat.has.Nat,
    E7,
    Input7 <: xio.nat.has.Nat,
    E8,
    Input8 <: xio.nat.has.Nat,
    E9,
    Input9 <: xio.nat.has.Nat,
    E10,
    Input10 <: xio.nat.has.Nat,
    E11,
    Input11 <: xio.nat.has.Nat,
    E12,
    Input12 <: xio.nat.has.Nat,
    E13,
    Input13 <: xio.nat.has.Nat,
    E14,
    Input14 <: xio.nat.has.Nat,
    E15,
    Input15 <: xio.nat.has.Nat,
    E16,
    Input16 <: xio.nat.has.Nat,
    E17,
    Input17 <: xio.nat.has.Nat,
    E18,
    Input18 <: xio.nat.has.Nat,
    E19,
    Input19 <: xio.nat.has.Nat,
    E20,
    Input20 <: xio.nat.has.Nat,
    E21,
    Input21 <: xio.nat.has.Nat,
    E22,
    Input22 <: xio.nat.has.Nat,
    Input <: xio.nat.has.Nat,
    Out
  ](
    e1: xio.ErrorContent[E1, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e2: xio.ErrorContent[E2, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e3: xio.ErrorContent[E3, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e4: xio.ErrorContent[E4, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e5: xio.ErrorContent[E5, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e6: xio.ErrorContent[E6, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e7: xio.ErrorContent[E7, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e8: xio.ErrorContent[E8, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e9: xio.ErrorContent[E9, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e10: xio.ErrorContent[E10, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e11: xio.ErrorContent[E11, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e12: xio.ErrorContent[E12, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e13: xio.ErrorContent[E13, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e14: xio.ErrorContent[E14, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e15: xio.ErrorContent[E15, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e16: xio.ErrorContent[E16, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e17: xio.ErrorContent[E17, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e18: xio.ErrorContent[E18, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e19: xio.ErrorContent[E19, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e20: xio.ErrorContent[E20, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e21: xio.ErrorContent[E21, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    e22: xio.ErrorContent[E22, P] => xio.XIO[xio.XHasM22[
      Input,
      Input1,
      Input2,
      Input3,
      Input4,
      Input5,
      Input6,
      Input7,
      Input8,
      Input9,
      Input10,
      Input11,
      Input12,
      Input13,
      Input14,
      Input15,
      Input16,
      Input17,
      Input18,
      Input19,
      Input20,
      Input21
    ]#InnerPlus[Input22], P, Out],
    u: xio.XError22[E1, E2, E3, E4, E5, E6, E7, E8, E9, E10, E11, E12, E13, E14, E15, E16, E17, E18, E19, E20, E21, E22]
  ): xio.XIO[xio.XHasM22[
    Input,
    Input1,
    Input2,
    Input3,
    Input4,
    Input5,
    Input6,
    Input7,
    Input8,
    Input9,
    Input10,
    Input11,
    Input12,
    Input13,
    Input14,
    Input15,
    Input16,
    Input17,
    Input18,
    Input19,
    Input20,
    Input21
  ]#InnerPlus[Input22], P, Out] =
    u.either.fold(
      ii1 => errorCompat21(e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, ii1),
      ii2 => e22(new xio.ErrorContentImpl(ii2))
    )
}
